### ISSUE TITLE
Review typography

### ISSUE THREAD

**Issue by joshwnj** [x-team/auto-ui#42]
Now that many of the components are in place, we need to do a review of the sketch file and ensure we are using the correct font faces / sizes / spacing.

**Comment by bernardodiasc** [comment]
Note that the best approach for this task is to firstly include all base values in 
[src/styles/theme.js](https://github.com/x-team/auto-ui/blob/master/src/styles/theme.js) (related to https://github.com/x-team/auto-ui/issues/25) and then using these values on [src/styles/typo.js](https://github.com/x-team/auto-ui/blob/master/src/styles/typo.js) by creating all the typography patterns there.

It would be great to have all typography patterns in a single place, and also ensure to reset/override all browser default values for typography, specially for heading tags.

Also, in cases where relative units are used, it will be needed to make sure that the Root element of the component have a declaration of the font-size using `rem`, because that will ensure the relativity is correct (i.e. `font-size: 1rem;` in the component root is fine). --- But this is complex approach, I'd suggest to simply use fixed units like `px` instead, for everything.

**Comment by nicksp** [comment]
I agree with such initiative... at the moment there are several inconsistent usages of typography vars, colors, etc. And to ensure such consistency and make a solid use of theme variables instead, we should aim at better typography investigation and properly define them to cover every possible use case for any of the components. My suggestion is to start doing it gradually. First, probably we can start with analyzing existing UI components for typography/colors duplications/intersections. Then, adjust our `theme.js` and `typo.js` files to reflect those findings. The last step would be going through components one by one (one component - one new PR) and make use of newly defined variables. Wdyt guys?

**Comment by joshwnj** [comment]
Yes I think an incremental approach is best here.

We're dealing with the DRY principle here, and so it's helpful to remember why repetition is a problem in the first place.  Here's the thing: repetition is actually fine. Computer doesn't care. The time that it matters is when we want to change things.  

As we are not planning a lot of changes in the near future, we don't even need to spend too long analysing the codebase as a whole. We can just target one point of repetition at a time.

**Comment by nicksp** [comment]
Since, this is kinda important to have upfront, going to tackle this :-) Will try to put it in an easy way 😛
